### ISSUE TITLE
#TF001 Verificar que el usuario acceda a la aplicación correctamente.

### ISSUE THREAD

**Issue by g3rm6n** [PPI-GNCR/Proyecto_IOT#1]
En el caso que el Usuario ingrese correctamente sus credenciales, 
cuando oprima el botón "Iniciar sesión",
a continuación la aplicación valida su autenticidad y es direccionado a la pantalla de "Productos".
Precondiciones:	La cuenta del usuario debe existir y estar activa.
Datos de Prueba:	Correo: admin@admin.com	Contraseña: admin	 	 
Pasos:	1. Abrir la app.	2. Ingresar el correo electrónico en el campo correspondiente	3. Ingresar contraseña en el campo correspondiente	4. Oprimir el botón "Iniciar sesión"
Resultado Esperado:	El sistema verifica las credenciales y redirige al catálogo de productos si son correctas.
Pass/Fail:	 FAIL
Prioridad:		Crítica
#Etiquetas:	#Prueba de Funcionalidad #Prueba de Integración #caja negra

**Comment by g3rm6n** [comment]
Diseñado por:  Fernando Barletta
Ejecutado por:   Fernando Barletta

**Comment by Roryx1** [comment]
Esta issue fue borrada por no corresponder al proyecto
