### ISSUE TITLE
#TF006	Verificar que el usuario pueda enviar un mensaje a través del formulario de contacto solo si todos los campos están completados correctamente.

### ISSUE THREAD

**Issue by g3rm6n** [PPI-GNCR/Proyecto_IOT#6]
Cuando el usuario completa correctamente todos los campos requeridos (nombre, correo electrónico y mensaje) y oprime ""Enviar"", el sistema envía el formulario y muestra un mensaje de confirmación de envío exitoso		
Precondiciones:	El formulario de contacto debe estar accesible desde la aplicación		
Datos de Prueba:	Nombre: Juan Pérez	Correo Electrónico: juan@example.com	Mensaje: Consulta sobre el producto XYZ
Pasos:	1. Navegar a la pantalla de contacto.	2. Ingresar un nombre válido, correo electrónico y mensaje en el formulario.	3. Hacer clic en el botón "Enviar".
Resultado Esperado:	El sistema envía el formulario y muestra un mensaje de confirmación de envío exitoso.		
Pass/Fail:	NOT RUN		
Prioridad:	Baja		
#Etiquetas:	#Prueba de Funcionalidad #Prueba de Usabilidad #Caja Negra

**Comment by g3rm6n** [comment]
Diseñado por:	Federico Krenn		
Ejecutado por:	Federico Krenn

**Comment by Roryx1** [comment]
Esta issue fue borrada por no corresponder al proyecto
