### ISSUE TITLE
#TF008             Acceso a detalles del producto en la página de producto	

### ISSUE THREAD

**Issue by g3rm6n** [PPI-GNCR/Proyecto_IOT#8]
Verificar que al seleccionar un producto de la lista, se muestren correctamente todos los detalles (nombre, precio, fotos, talle, color, etc.) en la página de detalles del producto.	
Precondiciones:	El usuario debe estar navegando por la lista de productos	
Datos de Prueba:	Producto: Bicicleta de montaña	
Pasos:	1. Seleccionar un producto de la lista (por ejemplo, Bicicleta de montaña)	2. Revisar los detalles mostrados (nombre, precio, fotos, talle, color, etc.)
Resultado Esperado:	Los detalles del producto seleccionado (nombre, precio, fotos, talle, color) se muestran correctamente.	
Pass/Fail:     FAIL	
Prioridad:    Alta	
#Etiquetas:	#Productos #Detalles

**Comment by g3rm6n** [comment]
Diseñado por:	Fernanda Castillo	
Ejecutado por:	Fernanda Castillo

**Comment by Roryx1** [comment]
Esta issue fue borrada por no corresponder al proyecto
